DROP TABLE IF EXISTS tblmoviesrating;
CREATE TABLE IF NOT EXISTS tblmoviesrating(
id SERIAL PRIMARY KEY,
  rating NUMERIC(5,2) NOT NULL,
  movie_id INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DROP TABLE IF EXISTS comments;
CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  movie_id INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);