DROP TABLE IF EXISTS tblmoviesrating;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS comments;


CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tblmoviesrating(
  id SERIAL PRIMARY KEY,
  rating NUMERIC(5,2) NOT NULL,
  movie_id INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  movie_id INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);